[workspace]

members = [
    "zodiac_examples",
    "zodiac",
    "zodiac_layout",
    "zodiac_entities",
    "zodiac_parsing",
    "zodiac_resources",
    "zodiac_rendering",
    "zodiac_rendering_glium"
]
