[workspace]

members = [
    "zodiac",
    "zodiac_html",
    "zodiac_rendering_html_webrender",
    "zodiac_zoml",
    "zodiac_rendering_zoml_glium",
    "zodiac_hotloading",
    "examples\\hotloading\\app_runner",
    "examples\\hotloading\\app",
    "examples\\hotloading\\app_state"
]
