[package]
name = "zodiac"
version = "0.1.0"
authors = ["sammosampson <sammosampson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.3.1"
rayon = "1.5"
glium = "*"
zodiac_entities = {path = "../zodiac_entities", version = "0.1.0"}
zodiac_parsing = {path = "../zodiac_parsing", version = "0.1.0"}
zodiac_resources = {path = "../zodiac_resources", version = "0.1.0"}
zodiac_rendering = {path = "../zodiac_rendering", version = "0.1.0"}
zodiac_rendering_glium = {path = "../zodiac_rendering_glium", version = "0.1.0"}